### ISSUE TITLE
Possibility of having changelog.

### ISSUE THREAD

**Issue by eshepelyuk** [nvimtools/none-ls.nvim#2]
Is it possible to start maintaining some sort of changelog / version history / release history ?

**Comment by mochaaP** [comment]
Keeping a clean commit log is the best changelog, in my honest opinion. :P

If we really need a release history, we should also consider when to do a stable release (monthly?), as the development cycle is rolling quick for such a project.

**Comment by smjonas** [comment]
Release-please could be used to allow versioning of this plugin and it can generate a changelog as well. See e.g. folke's lazy.nvim.

**Comment by mochaaP** [comment]
If we release a version just within a few commits, then I couldn't see the point of doing this. In the case of avoiding breaking changes, I'd rather prefer to develop that on a different branch and transition to it gracefully.
I encourage the state of "if you believe something is wrong, open a PR" instead of pinning to "stable" commits.

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-null-ls.nvim/blob/main/.github/workflows/ci.yml#L37 - versioning seems like another headache for maintenance but using this github workflow, I would recommend it as it just involves merging a pull request when ready to release. the version numbers are handled for you

**Comment by ambroisie** [comment]
Rather thank ask for a changelog, it would be nice to do like some other plug-ins and create a (locked) issue which gets updated with a new comment when a breaking change is merged in.
